// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package dk.aau;

// import javafx.collections.FXCollections;
// import javafx.collections.ObservableList;
// import dk.aau.model.*;
// import dk.aau.view.*;
// import dk.aau.controller.*;


// public class App {
//     public String getGreeting() {
//         return "Hello world.";
//     }

//     public static void main(String[] args) {
//         System.out.println(new App().getGreeting());
//     }
//     private ObservableList<ReferralListModel> referralList = FXCollections.observableArrayList();

//         referralList.add(new ReferralListModel("Hans", "233492-1233"));
//         referralList.add(new ReferralListModel("Ruth", "290506-1236")) ;
//         referralList.add(new ReferralListModel("Heinz", "311200-9561"));
//         referralList.add(new ReferralListModel("Cornelia", "290483-2096"));
//         referralList.add(new ReferralListModel("Werner", "192835-1023"));
//         referralList.add(new ReferralListModel("Lydia", "101039-5302"));
//         referralList.add(new ReferralListModel("Anna", "240140-1028"));
//         referralList.add(new ReferralListModel("Stefan", "120594-5961"));
//         referralList.add(new ReferralListModel("Martin", "150919-5910"));

//         public ObservableList<ReferralListModel> getreferralList() {
//             return referralList;
//         }
 //}

//}